### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by tay45** [ablab/tandemQUAST#7]
Hello,

I have an installation issue. When running 'conda install --file requirements.txt', I got the PackagesNotFoundError for the 'jellyfish' and 'edlib'. The 'jellyfish' was separately installed via conda, but the 'edlib' was failed to be installed using conda, separately. Instead I installed it via pip3 install edlib. However, when trying to run the tool usding the test datasets, it wasn't properly working. I attacehd the log as below. Could you give some advice to figure out the issue? Thank you.

$ /Users/thkang/TandemTools/tandemquast.py --nano /Users/thkang/TandemTools/test_data/simulated_reads.fasta /Users/thkang/TandemTools/test_data/simulated_polished.fa -o simulated_res
Traceback (most recent call last):
  File "/Users/thkang/TandemTools/tandemquast.py", line 12, in <module>
    from scripts import polishing
  File "/Users/thkang/TandemTools/scripts/polishing.py", line 7, in <module>
    from ext_tools.Flye.flye.polishing.polish import polish
  File "/Users/thkang/TandemTools/ext_tools/Flye/flye/polishing/polish.py", line 28, in <module>
    from scripts.utils import get_ext_tools_dir
  File "/Users/thkang/TandemTools/scripts/utils.py", line 12, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by Rashadx86** [comment]
Hi,

I encountered the same installation error for jellyfish and edlib. Adding bioconda and conda-forge to my list of conda repositories did the trick:

conda config --append channels bioconda
conda config --append channels conda-forge
